---
- name: install snapd
  apt:
    name:
      - snapd
      - fuse
      - squashfuse
    update_cache: true

- name: ensure snap service is running
  service:
    name: snapd
    state: started
    enabled: true

- name: wait for snapd to be ready
  command: snap find test
  retries: 3
  delay: 30
  register: result
  until: result.rc == 0
  tags:
    - skip_ansible_lint

- name: Install snap packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.use_classic }}"
  with_items: "{{ snap_packages }}"
